### ISSUE TITLE
Which version of terraform is this repository using?

### ISSUE THREAD

**Issue by pravink** [pelias/terraform-elasticsearch#3]
Hi there,

I am trying to use this module as a terraform module but facing Missing key/value separator issue with files checked in here.

I have specified this as a source to my module. 
I am using terraform v0.12.7
does above repository supports this version? or do i need to fall down to specific version of terrafom?

thanks,
Pravin!

**Comment by pravink** [comment]
Thanks for a quick reply.. 

I was trying with v0.11.14 and its working as expected.. though has some other issues with installing elb which cant be attached to multiple subnets in same AZ. if you have encountered this issue before do let me know the fix.

**Comment by orangejulius** [comment]
Hi @pravink,
We just ran into this issue ourselves. Turns out it is a bug in our terraform code. There's a full description over in https://github.com/pelias/terraform-elasticsearch/issues/12, in the meantime you just have to set some `tags` for the module as described in the issue and also the main README
